### PR TITLE
:memo: memo loadinstance

### PR DESCRIPTION
**Pull request by landryarki**
Added a memo on how to use loadInstance.
Draft at the moment because it could be updated in the near future.

### CODE REVIEW

**Review by mathieurobert1 — APPROVED** [review]
Seems good :+1:

**Review by Njord201 — APPROVED** [review]
:+1:

**Review by AubaneNourry — APPROVED** [review]

**Review by Thomaltarix — APPROVED** [review]
Great job !

**Review by theophile-jr — APPROVED** [review]

**Review by 6im0n — APPROVED** [review]
good for me !

**Review by Peralban — COMMENTED** [review]
:+1:

**Review by Peralban — APPROVED** [review]

**Pull request merged**
