### PR TITLE
Refacto typo: Name of keys.hpp file to Keys.hpp

### PR DESCRIPTION
**Pull request by Peralban**
:pencil2: Little change on keys.hpp name

### CODE REVIEW

**Review by 6im0n — APPROVED** [review]
Ok good for me !

**Review by mathieurobert1 — APPROVED** [review]
:+1:

**Review by Quentintnrl — APPROVED** [review]

**Review by Thomaltarix — APPROVED** [review]
Great

**Review by Njord201 — APPROVED** [review]
:+1:

**Review by theophile-jr — APPROVED** [review]

**Review by landryarki — APPROVED** [review]
yes

**Review by AubaneNourry — APPROVED** [review]

**Pull request merged**
