### PR TITLE
Added key event gestion

### PR DESCRIPTION
**Pull request by landryarki**
added two new methods:
std::pair<int, int> getMouseEvent();
void catchMouseEvent(int x, int y);

and two new "keys":
Keys::MOUSE_LEFT
Keys::MOUSE_RIGHT

### CODE REVIEW

**Review by mathieurobert1 — APPROVED** [review]
Seems good :+1:

**Review by Thomaltarix — CHANGES_REQUESTED** [review]
I think you could rename `Events` by `Positions` since you get the mouse events (Left or Right click) using the `getKeyEvent` method

**Review by Peralban — APPROVED** [review]

**Review by 6im0n — APPROVED** [review]
Good for me !

**Review by Thomaltarix — APPROVED** [review]
:ok_hand:

**Review by Njord201 — APPROVED** [review]

**Review by AubaneNourry — APPROVED** [review]

**Pull request merged**
