### PR TITLE
🎨 add namespace to the interface

### PR DESCRIPTION
**Pull request by Quentintnrl**
I propose to add this namespace for the interfaces

### CODE REVIEW

**Review by 6im0n — APPROVED** [review]
Good for me !

**Review by mathieurobert1 — APPROVED** [review]
Seems good :+1:

**Review by Njord201 — APPROVED** [review]

**Review by AubaneNourry — APPROVED** [review]

**Review by Thomaltarix — APPROVED** [review]
Great job

**Review by theophile-jr — APPROVED** [review]

**Review by landryarki — APPROVED** [review]

**Review by Peralban — APPROVED** [review]
Good for me 👍

**Pull request merged**
